### ISSUE TITLE
XML Syntax Highlighting doesn't work in some scenarios

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#39]
_From @pierrepaullavoie on April 20, 2014 4:48_

The default `XML.tmLanguage` file will not recognize XML attributes in any of the three following scenarios below.

The language file `<key>tagStuff</key>` regular expression could be updated with: `[\s](?:([-_a-zA-Z0-9]+)((:)))?([-_.a-zA-Z0-9]+)[\s]*=` to solve those problems.

Original regular expression: ` (?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9]+)=`.

##### Attribute name includes a period

    foo.1="bar"

##### If you have a space after the attribute name:

    foo ="bar"

##### If the element names previous character is not a space character:

    \tfoo="bar"

or

    \nfoo="bar"

_Copied from original issue: SublimeTextBugs/Issues#272_

**Comment by keith-hall** [comment]
Looks like `\tfoo="bar"` and `foo.1="bar"` have been fixed in these commits: https://github.com/sublimehq/Packages/commit/63620e55e4d79a4470e38bb0d6e16fc4e95fef91 and https://github.com/sublimehq/Packages/commit/fe943080e895bfbeedd5f6277dbacef33474b7ab
still leaves `\nfoo="bar"` and `foo ="bar"` to be fixed

**Comment by FichteFoll** [comment]
`foo ="bar"` is explicitly tracked in https://github.com/SublimeTextIssues/DefaultPackages/issues/93 and has been fixed via https://github.com/sublimehq/Packages/pull/308/commits/9b449a718232720740183fb6fcbfd54d42766a41.

I didn't check `\nfoo="bar"` however. @keith-hall?

**Comment by keith-hall** [comment]
`\nfoo="bar"` isn't fixed yet. Technically, `\nfoo\n=\n"bar"` is also valid, and will require more work - I think it makes sense to fix these at the same time.

**Comment by keith-hall** [comment]
I decided to tackle the original issue of `\nfoo="bar"` separately and first :)

**Comment by FichteFoll** [comment]
Yes, please do that.

**Comment by keith-hall** [comment]
This issue can now be closed then, my change for `\nfoo="bar"` has just been merged :+1:
